### ISSUE TITLE
[Question] Constant efficiency mode

### ISSUE THREAD

**Issue by newmandb** [JohannesBuchner/UltraNest#115]
Is there a mode analogous to the 'constant efficiency' mode of MultiNest, or other settings recommended when parameter estimation is desired (but not evidence calculation) and the sampling efficiency is low (due to high dimensionality)?

Thanks for any advice.

**Comment by JohannesBuchner** [comment]
'constant efficiency' mode of MultiNest is not really safe and can lead to biases. UltraNest has as a design goal to give reliable inference, not quick look results. You could reduce the num_bootstraps parameter or use a slice sampler with a very low number of steps to achieve this. Depending on the problem, you can also get fast results with a Laplace approximation, https://johannesbuchner.github.io/snowline/ or MCMC ensembles https://johannesbuchner.github.io/autoemcee/

**Comment by newmandb** [comment]
Thank you!
