### ISSUE TITLE
Reproducibility of UltraNest fits

### ISSUE THREAD

**Issue by comane** [JohannesBuchner/UltraNest#117]
* UltraNest version: 3.6.2
* Python version:3.10.12 
* Operating System: MacOS (and linux)

### Description
Ultranest fits seem not to be reproducible. When running twice the same fit I don't get exactly the same results.
Is there a random seed that can be fixed in order to control this?

**Comment by JohannesBuchner** [comment]
Yes, you can set the numpy random seed. Try without parallelisation first.

**Comment by comane** [comment]
Thanks, it does work indeed.
