### ISSUE TITLE
"ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'long'" (Windows compatibility issue?)

### ISSUE THREAD

**Issue by nsusemiehl** [JohannesBuchner/UltraNest#12]
* UltraNest version: 2.2.1
* Python version: 3.7
* Operating System: Windows 10

### Description

I was trying to fit a line to simulated data when I encountered the the error "ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'long'". This occured after the line "result = sampler.run(min_num_live_points=50, min_ess=100)". I have pasted the full code I was using below. I encountered the same issue while running UltraNest's basic usage demo and line fitting tutorial.

```
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats
import ultranest
from ultranest.plot import cornerplot

x_true = np.linspace(0,10, 1000)
slope_true = 2
int_true = 3
y_true = x_true * slope_true + int_true

N = 25
x_sample = np.random.choice(x_true, N)
y_sample = x_sample * slope_true + int_true

dispersion_true = 0.5
x_err = np.random.normal(0, dispersion_true, size = N)
y_err = np.random.normal(0, dispersion_true, size = N)

x = x_sample + x_err
y = y_sample + y_err

parameters = ['slope', 'intercept', "dispersion"]

def prior_transform(cube):
    # the argument, cube, consists of values from 0 to 1
    # we have to convert them to physical scales

    params = cube.copy()

    lo = -0
    hi = +4
    params[0] = cube[0] * (hi - lo) + lo

    lo = 1
    hi = 5
    params[1] = cube[1] * (hi - lo) + lo

    lo = 0
    hi = 2
    params[2] = cube[2] * (hi - lo) + lo

    return params

def log_likelihood(params):

	slope, intercept, dispersion = params
	dispersion = max(dispersion, 0)

	model_y = x * slope + intercept
	data_y = y_sample
	error = dispersion**2 + y_err**2 + (slope * x_err)**2

	ll = np.nan_to_num(-0.5 * sum(np.power(np.subtract(data_y, model_y), 2) / np.power(error, 2)))

	return ll

sampler = ultranest.ReactiveNestedSampler(parameters, log_likelihood, prior_transform)
result = sampler.run(min_num_live_points=50, min_ess=100)
cornerplot(sampler.result)

```
### What I Did
I was not able to find any information on this error code online specific to UltraNest, but this issue seems to arise in other packages that depend on cython for Windows users. I installed a development version of UltraNest via pip and edited lines 1451 and 1452 of ultranest's integrator.py to be dtype=np.int64 instead of dtype=int, but this did not fix the issue. Are there any known compatibility issues between UltraNest and Windows?

Crash report:
```
Traceback (most recent call last):
  File "test2.py", line 68, in <module>
    result = sampler.run(min_num_live_points=50, min_ess=100)
  File "c:\users\nsuse\ultranest\ultranest\integrator.py", line 1788, in run
    viz_callback=viz_callback,
  File "c:\users\nsuse\ultranest\ultranest\integrator.py", line 1971, in run_iter
    minvol=exp(main_iterator.logVolremaining))
  File "c:\users\nsuse\ultranest\ultranest\integrator.py", line 1492, in _update_region
    nextTransformLayer = self.transformLayer.create_new(active_u, self.region.maxradiussq, minvol=minvol)
  File "ultranest\mlfriends.pyx", line 502, in ultranest.mlfriends.AffineLayer.create_new
  File "ultranest\mlfriends.pyx", line 199, in ultranest.mlfriends.update_clusters
  File "ultranest\mlfriends.pyx", line 48, in ultranest.mlfriends.find_nearby
ValueError: Buffer dtype mismatch, expected 'int64_t' but got 'long'
```

**Comment by JohannesBuchner** [comment]
That is a strange error indeed.

Could you try the following:

```
u = np.random.uniform(size=3)
p = prior_transform(u)
print(p)
print(p.dtype)
L = log_likelihood(u)
print(L)
print(L.dtype)
```

I would have written the line

```
ll = np.nan_to_num(-0.5 * sum(np.power(np.subtract(data_y, model_y), 2) / np.power(error, 2)))
```
as
```
ll = -0.5 * (((data_y - model_y) / error)**2).sum()
ll[~(ll > -1e300)] = -1e300
```

**Comment by nsusemiehl** [comment]
Thanks for your quick response!

I changed ll to be as you suggested and ran the code you suggested in my test file. Here is the output:

"[3.172712   1.54612034 1.69828307]

float64

Traceback (most recent call last):
  File "test2.py", line 104, in <module>
    L = log_likelihood(u)
  File "test2.py", line 74, in log_likelihood
    ll[~(ll > -1e300)] = -1e300
TypeError: 'numpy.float64' object does not support item assignment"

I also ran that code chunk in the same file as where I was working with UltraNest's Basic Usage demo. Here is the output of that:

"[7.07855595e+02 1.75399069e-01 1.30616662e-01]
float64
-410.3593936078883
float64"

**Comment by JohannesBuchner** [comment]
Oh, I was silly. It should be in your case:

```
if not ll > -1e300: 
    return -1e300
return ll
```

**Comment by nsusemiehl** [comment]
Here is the result from my test file using that modification:

[3.31298703 3.1134615  0.93358461]
float64
-5217.5246703298
float64

**Comment by JohannesBuchner** [comment]
I see, I think your code is fine. I guess the error also occurs with a trivial gaussian likelihood.

I never tried on windows, actually. The default dtypes are likely different, and this causes issues. You may need to play a bit with the [dtypes](https://numpy.org/doc/stable/user/basics.types.html).

Don't forget to rebuild the extension after you modify cython code, if you run the code in-place. I usually use `python3 setup.py build_ext --inplace`.

**Comment by JohannesBuchner** [comment]
Could you try the following two modifications:

1. replace all dtype=np.int64_t with dtype=int
2. replace all dtype=int with dtype=np.int64

I am not sure the first option works.

**Comment by nsusemiehl** [comment]
I tried replacing the two instances of `dtype=int` in integrator.py with `dtype=np.int64` and `dtype=np.int64_t`. After saving integrator.py each time, I ran `python setup.py build_ext --inplace` in my ultranest folder. I'm still getting the same error unfortunately. Should I try making this modification in other files as well?

**Comment by JohannesBuchner** [comment]
I think you only need to make mlfriends.pyx internally consistent. In the function declaration it uses int64_t, but in the lower functions it uses dtype=int. I suspect windows chooses the C type long instead of int64_t (used in Linux) when numpy allocates an array with "dtype=int". Then when the declared function is called, there is a mismatch.

**Comment by JohannesBuchner** [comment]
I expect that changing this line: https://github.com/JohannesBuchner/UltraNest/blob/master/ultranest/mlfriends.pyx#L51 
to `np.ndarray[np.int_t, ndim=1] nnearby` should work? Same for line 17. And keep everything else the same as it was (dtype=int).

**Comment by nsusemiehl** [comment]
Awesome, that worked! I reverted all of the changes I made to lines 1451 and 1452 of integrator.py (put them back to dtype=int), changed lines 17 and 51 of mlfriends.pyx  to `np.ndarray[np.int_t, ndim=1] nnearby`, then ran `python setup.py build_ext --inplace` in my UltraNest folder. My code now runs without errors. Thanks so much for your help!

**Comment by JohannesBuchner** [comment]
Can you submit a pull request? (Fork the repository, make a git commit, and open a pull request to this repo)
(If too complicated, no problem, I can do it myself.)

**Comment by nsusemiehl** [comment]
Just submitted the pull request.

**Comment by JohannesBuchner** [comment]
Thanks for the information and the pull request!

Please test with the new release 2.2.2 whether UltraNest now runs through and does the entire integration correctly.

**Comment by JohannesBuchner** [comment]
I think this is fixed, if not, please reopen.
