### ISSUE TITLE
Add ESS calculation to static version results

### ISSUE THREAD

**Issue by Joshuaalbert** [JohannesBuchner/UltraNest#122]
@JohannesBuchner we really need you to add ESS to the static implementation results, when `num_live_points>0` for cross comparison in a paper. Can you quickly add this, or point me how to do this simply?

**Comment by JohannesBuchner** [comment]
I don't understand. 'ess' should be in the results dictionary.

**Comment by JohannesBuchner** [comment]
Please reopen if this is still an issue.
