### ISSUE TITLE
Best way to load results dict?

### ISSUE THREAD

**Issue by nstarman** [JohannesBuchner/UltraNest#128]
* UltraNest version: 4.3.0
* Python version: 3.12
* Operating System: MacOS

### Description

More of a general question, if I have running NS (on resume-similar) but I want to make a corner plot while it's still running, what's the best way to load up the full results in another notebook? Is there a way to do this without constructing a full Sampler, which complains about locked files?

**Comment by JohannesBuchner** [comment]
Have a look at this function: https://johannesbuchner.github.io/UltraNest/ultranest.html#ultranest.integrator.read_file

**Comment by nstarman** [comment]
thank you!
