### ISSUE TITLE
n subfolders are created when running on n cores

### ISSUE THREAD

**Issue by ThomasKonings** [JohannesBuchner/UltraNest#144]
* UltraNest version: 3.4.4
* Python version: 3.9.19
* Operating System: Linux

I am having trouble when running ultranest in parallell with `mpirun -np n python myscript.py`. I have put `resume='subfolder'` in the ReactiveNestedSampler function.

n subfolders are created, from run1 to runn, instead of just one single output subfolder. However, sometimes (for unknown reasons) it does create a single subfolder. I don't change anything regarding the set-up/environment/code that can justify that the code switches between creating n subfolders, or creating a single subfolder.

I also do not understand the meaning of the results in every of those n subfolders, as one final output is needed.

Thank you in advance!

p.s. I am noticing similarities with Issue #27 , which seems to request a functionality that creates exactly n subfolders instead of one.

**Comment by JohannesBuchner** [comment]
Have a look at https://johannesbuchner.github.io/UltraNest/debugging.html#Parallelisation-issues 
and make sure mpi4py is installed.
