### ISSUE TITLE
FloatingPointError: underflow encountered in exp

### ISSUE THREAD

**Issue by ParashmoniKashyap** [JohannesBuchner/UltraNest#147]
* UltraNest version: 4.3.2
* Python version: 3.10.14
* Operating System: Ubuntu 22.04

### Description
I am trying to fit a model using ultranest. Following is the error I am getting.

 File ~/Softwares/DRIVE/sampler.py:491 in run_ultranest
    result = sampler.run(dlogz=dlogz, min_num_live_points=nlivepoints,

  File ~/Softwares/anaconda3/envs/pegasis/lib/python3.10/site-packages/ultranest/integrator.py:2452 in run
    for _result in self.run_iter(

  File ~/Softwares/anaconda3/envs/pegasis/lib/python3.10/site-packages/ultranest/integrator.py:2815 in run_iter
    main_iterator.passing_node(rootid, node, active_rootids, active_values)

  File ~/Softwares/anaconda3/envs/pegasis/lib/python3.10/site-packages/ultranest/netiter.py:852 in passing_node
    self.all_logZremain = V + log(np.sum(exp(parallel_values - Lmax))) + Lmax

FloatingPointError: underflow encountered in exp

### What I Did
parallel values are essentially likelihood values as far as I understood. I tried printing 
params values, likelihood value, and (parallel_values - Lmax)

Typical params (theta) and log-likelihood:

theta: [ 3.21277698e+01  1.91600310e+01 -9.46219491e-01 -2.93745113e-01
  4.67826984e-01  6.48686614e+00 -3.80272136e+00  1.67440482e-03]
log_likelihood: -1.1023200864295015e+20
**************************************************
theta: [ 3.29130907e+01  1.35401007e+01 -9.67695992e-01 -3.12244440e-01
  4.70838577e-01  6.57129455e+00 -3.74575494e+00  1.52073891e-03]
log_likelihood: -7.896440175726198e+18
**************************************************
theta: [ 1.86676316e+01  4.72708168e+01 -5.49938681e-01 -2.12651687e-01
  5.28899222e-01  8.46616123e+00 -3.39521753e+00  6.85847662e-04]
log_likelihood: -5.246160732436559e+16
***********************************************
.
.
.

theta: [ 2.78449189e+01  2.05217225e+01 -8.69926654e-01 -2.89311773e-01
  4.76352643e-01  7.26655064e+00 -3.61982622e+00  1.16953826e-03]
log_likelihood: -3.9850477312963576e+16

And the corresponding (parallel_values - Lmax) values
[-9.15834850e+12 -4.02855677e+12 -2.16132921e+13 -1.56872958e+12
 -2.51405382e+12 -2.91081833e+12 -7.87729724e+11 -2.88328852e+23
 -7.88521884e+12 -2.21289743e+11 -7.15613590e+14 -1.17939483e+11
 -6.46708489e+11 -2.23752379e+14 -2.24181794e+12 -6.71306554e+12
 -1.15464337e+13 -2.58716024e+13 -2.80353277e+12 -3.60058777e+14
 -2.34515280e+12 -3.01841794e+12 -9.14464973e+11 -3.58137060e+12
 -1.57687238e+11 -2.19950504e+11 -3.55325666e+11 -2.00262358e+13
 -1.62960176e+10 -7.28596063e+12 -1.66834817e+11 -3.49651718e+12
 -3.13286985e+13 -2.72269929e+11 -5.27923132e+07 -1.88226285e+11
 -1.52164793e+12 -1.94639644e+13 -7.01731620e+12 -2.33661639e+12
 -1.09120638e+13 -2.09667842e+14 -1.06491659e+13 -1.37529745e+11
 -1.45093898e+13 -2.41640837e+12 -4.09723308e+13 -8.48362013e+12
 -5.58277921e+13 -3.45641048e+11 -4.74458587e+14 -1.12866840e+14
 -1.71996824e+15 -4.77630238e+13 -6.59287567e+12 -5.72815433e+13
 -2.65822952e+12 -5.06683726e+12 -3.43820383e+11 -2.33673500e+12
 -8.17208521e+11 -6.44175910e+13 -1.71129017e+15 -5.87893442e+11
 -9.06817710e+11 -6.95808580e+11 -1.75754652e+13 -1.32023231e+13
 -2.36942081e+13 -4.84633715e+11 -5.71095700e+14 -8.82813105e+12
 -1.29750265e+15 -2.49746535e+16 -1.20407003e+13 -5.68576371e+13
 -1.80345662e+13 -1.97366290e+13 -1.01375410e+12 -9.46767954e+12
 -7.20434860e+12 -1.03799601e+13 -1.20057451e+09 -1.51149599e+20
 -1.83923935e+10 -5.66868452e+07 -3.89350470e+12 -7.53166357e+14
 -3.25339042e+13 -2.99911020e+12 -5.47196218e+11 -1.45271754e+12
 -1.45158099e+12 -7.37434922e+14 -3.75837761e+12 -7.05851715e+12
 -1.10598610e+14 -3.83840819e+15 -2.88772893e+13 -4.42483974e+13
 -4.06170705e+14 -7.80428115e+11 -1.03137568e+13 -3.62291091e+12
 -9.44209427e+11 -4.75738378e+12 -8.02303135e+10 -1.19636101e+12
 -4.20139678e+11 -1.95246536e+11 -2.72703516e+12 -4.59999937e+12
 -7.34750312e+10 -3.32729313e+10 -1.70176124e+13 -1.06299037e+11
 -3.20351137e+10 -7.58291500e+13 -8.16460289e+13 -8.73818877e+14
 -2.24487576e+12 -1.68843041e+13 -7.51460045e+13 -1.12210663e+13
 -3.72004608e+12 -2.34975307e+12 -2.13788100e+13 -2.48970549e+13
 -3.00496725e+12 -3.37833175e+13 -2.78734736e+14 -8.81759539e+11
 -6.80077171e+13 -2.22795524e+13 -2.55632541e+15 -3.14618371e+12
 -1.00577315e+12 -3.81639219e+13 -6.71105336e+11 -4.01122738e+12
 -1.27918705e+09 -4.92421323e+13 -5.09621716e+13 -1.14776967e+13
 -1.82093570e+09 -2.46873470e+15 -4.67431565e+13 -3.86081072e+13
 -1.55106434e+13 -2.13003266e+12 -6.18655264e+11 -1.00657521e+15
 -2.27374914e+19 -2.64725733e+13 -3.57515864e+13 -1.14322829e+10
 -1.81973082e+12 -7.78143146e+12 -1.52390794e+10 -3.11663317e+13
 -9.62931142e+14 -1.83562935e+10 -5.88617421e+10 -3.79636774e+16
 -2.19658968e+18 -1.95355410e+13 -4.05612490e+13 -6.88560261e+12
 -3.24187341e+13 -2.67412728e+14 -1.22260098e+11 -1.55485282e+13
 -2.35224832e+13 -1.16293455e+13 -4.54287025e+13 -1.55363033e+13
 -3.11579251e+13 -6.43429856e+13 -2.44200009e+14 -1.16060715e+13
 -1.23837682e+13 -1.48143073e+12 -5.46252322e+14 -8.14551942e+12
 -2.79972548e+12 -2.87481560e+17 -1.03949994e+14 -5.16481834e+09
 -8.49611220e+12 -1.44654619e+15 -3.70975508e+13 -4.56142481e+12
 -2.45469842e+13 -4.20028197e+13 -1.23057014e+13 -2.75633272e+15
 -4.93533747e+12 -7.77833333e+10 -3.99961312e+09 -2.41622957e+11
 -1.38973981e+13 -4.96100575e+12 -8.73438272e+12 -1.73899682e+12
 -2.00198610e+13 -3.34840831e+12 -1.93284838e+14 -5.89957411e+13
 -2.43588645e+13 -2.09896073e+13 -9.99451425e+11 -1.89607945e+15
 -7.89154557e+11 -6.97135239e+11 -4.19334916e+14 -2.02692635e+13
 -5.53071713e+11 -1.05676867e+14 -3.06183527e+13 -2.51010728e+16
 -4.05748091e+14 -3.38878754e+12 -1.97746259e+13 -5.22356175e+12
 -2.58891118e+11 -1.95663025e+17 -3.16574860e+11 -1.04719703e+12
 -3.98097523e+09 -1.73962149e+11 -2.74722771e+11 -3.37644464e+13
 -5.04298456e+13 -1.24111598e+11 -1.27840526e+12 -1.83981783e+11
 -8.31062218e+11 -1.86363697e+13 -5.74440135e+15 -5.51150125e+10
 -2.56478961e+13 -1.41209354e+13 -1.43889509e+14 -1.15042165e+13
 -6.83867019e+14 -6.27358883e+13 -7.77314378e+10 -9.61601759e+14
 -3.74055888e+09 -6.59888437e+13 -4.45429011e+13 -2.15003290e+13
 -2.97242675e+12 -3.63113510e+10 -6.93565063e+11 -2.17567670e+14
 -2.16774110e+11 -4.33697294e+11 -3.66954879e+11 -1.28949500e+13
 -9.73084527e+12 -4.59015298e+12 -5.16237161e+12 -5.04665719e+17
 -9.63579563e+12 -2.13760822e+14 -1.04886075e+13 -2.26052117e+13
 -4.10501554e+12 -8.39096168e+11 -2.48625375e+13 -1.16260364e+13
 -7.96281124e+10  0.00000000e+00 -7.12699382e+12 -2.88273721e+13
 -6.56560205e+12 -2.66694245e+12 -1.05977004e+11 -2.41116222e+12
 -5.42004401e+15 -8.75158339e+14 -9.42110570e+11 -7.40511028e+10
 -2.05994090e+12 -1.52589528e+14 -1.12871723e+13 -4.91836487e+10
 -1.63646609e+13 -1.87578269e+13 -2.77971376e+15 -5.82859030e+12
 -3.82881582e+13 -1.77187970e+13 -2.15129481e+13 -2.35326114e+08
 -9.24192988e+12 -2.86870818e+13 -2.92189632e+16 -3.25667060e+12
 -1.04651133e+09 -1.42522540e+13 -1.26563440e+11 -7.75104206e+12
 -1.41942225e+13 -4.20670321e+12 -8.19454081e+11 -6.76738607e+14
 -4.16760126e+11 -1.56607649e+12 -1.09410883e+11 -1.84065664e+12
 -6.57689507e+08 -6.49473720e+12 -3.67391013e+14 -3.35208600e+14
 -5.26094800e+10 -2.87323446e+16 -1.48631744e+17 -4.80211481e+14
 -4.95865242e+11 -8.05384050e+14 -2.14610456e+13 -6.34448832e+10
 -3.63904246e+12 -1.45400691e+14 -1.28877631e+11 -7.05415132e+10
 -3.85252039e+12 -3.25547421e+13 -1.50122434e+18 -1.42624121e+11
 -6.95472187e+12 -6.91892543e+08 -1.07364211e+15 -2.98811456e+12
 -2.08011662e+11 -9.10161371e+09 -2.76297124e+13 -2.91022763e+12
 -9.70856960e+12 -1.08399772e+12 -2.22800193e+09 -4.34791786e+11
 -7.09451793e+11 -7.11509878e+13 -3.28010640e+14 -3.32713005e+12
 -1.46267313e+11 -1.86789749e+13 -1.06991588e+13 -9.13240291e+12
 -3.12901576e+13 -3.09012632e+11 -2.91176089e+12 -2.45856116e+11
 -1.57601735e+16 -1.98520782e+12 -1.87684273e+12 -7.58906542e+12
 -4.18465547e+12 -1.06430068e+14 -1.67437975e+11 -2.71636102e+17
 -3.32460738e+12 -1.86630655e+15 -3.20507051e+13 -7.80885020e+12
 -1.35087726e+13 -5.47250887e+11 -1.09509814e+13 -2.97360567e+13
 -1.53878528e+14 -1.09776698e+13 -5.04073790e+13 -3.04723189e+12
 -9.10309353e+13 -3.78299054e+11 -2.91429169e+13 -1.60392038e+12
 -5.03606240e+11 -1.38532988e+11 -4.89955410e+11 -1.71846402e+09
 -2.85684047e+12 -4.61997213e+12 -2.42205156e+14 -1.62657466e+12
 -1.52907198e+15 -2.22842029e+15 -7.05000184e+12 -5.27951842e+14
 -1.51231137e+12 -4.79555519e+12 -1.12860218e+13 -1.79241734e+09
 -1.06350972e+12 -2.80089931e+13 -8.03238094e+12 -1.89287871e+13]
```



```
    
The initial theta ranges for which uniform prior transform is defined:
```
theta_ranges = [[0, 90], [0, 360], [-1, 1], [-1, 1]] # inc, PA, xc, yc
theta_ranges += [[0.2, 0.6], [1e-3, 10], [0, -4], [1e-5, 1e-2]]
```

Only for this model do I get this error, not for other models. Please help me out. Is there anything I need to change in the model?

**Comment by JohannesBuchner** [comment]
The summation there tries to avoid issues with large floats by subtracting, then re-adding the highest value (Lmax). The very small floats won't be contributing but seem to raise an underflow error.

Probably that line in netiter.py:852 should be wrapped with `with np.errstate(under='ignore')`.

You can try some prior predictive checks to see if your model is okay, see https://johannesbuchner.github.io/UltraNest/example-sine-bayesian-workflow.html
