### ISSUE TITLE
Reading ultranest results without likelihood / cube transform

### ISSUE THREAD

**Issue by Tenivar** [JohannesBuchner/UltraNest#149]
* UltraNest version: 4.3.2
* Python version: 3.12
* Operating System: Debian

### Description

Hi, (I hope this question has not been answered before, but I did not find it ! )
I'm looking for a way to load Ultranest results from the log directory (e.g., to plot some diagnostics, corner plots, trace …) without having to provide a cube transform and a likelihood function, and “run” the nested sampler again (even if it actually just read the results). Is there a way to do that?
Thank you for the great tool and work :-)

**Comment by JohannesBuchner** [comment]
You are looking for this function: https://johannesbuchner.github.io/UltraNest/ultranest.html#ultranest.integrator.read_file

Maybe you can think about where you looked so that we can integrate it better in the documentation?

**Comment by JohannesBuchner** [comment]
Alternatively, you can also load the posterior samples as csv files.

**Comment by Tenivar** [comment]
Thanks a lot! 
I was actually looking for a function like ReactiveNestedSampler.load_results (in the same page you sent, my bad, I have not looked closely enough).
