### ISSUE TITLE
Occasionally biased output (not recovering true parameters of the model)

### ISSUE THREAD

**Issue by kotania** [JohannesBuchner/UltraNest#154]
* UltraNest version: 3.6.4
* Python version: 3.8.18
* Operating System: Rocky Linux release 9.4 (Blue Onyx)

### Description

I have a model with ~10-20 parameters, which generates binned data depending on the values of these parameters, with every bin representing a number of counts (>20 counts per bin, such that Gaussian statistics applies). I am trying to fit back the parameters of the model using a likelihood based on the χ2 metric and reasonable prior parameter ranges. The goal is to test sensitivity to some parameters of the model, given the correlations/degeneracies with other parameters and the statistical power of the mock data.

I am finding that the posterior maximum of some of the "important" parameters is biased, i.e., I am not perfectly recovering the true value. The deviation is small (~1-5% of the true parameter value), but somewhat significant in the realms of my model.

### What I Did

I am using a `ReactiveNestedSampler` with 400 livepoints and integrate until `frac_remain` of 0.01, although I also tried 0.001. I see that my "imperfectly recovered" parameter has mild correlations with some of the other parameters, so perhaps the imperfect recovery is related to getting stuck in a local minimum. 

Is there anything I can do to understand the origin of the bias and improve the recovery of the true parameter value?

**Comment by JohannesBuchner** [comment]
Is the maximum likelihood point found by the sampler (also stored in results, e.g. in info/results.json) distributed around the true value?

Volume effects of priors can cause the posterior median/mean to not be centered on the maximum likelihood. You can easily see that by imagining a L-shaped posterior distribution, and considering the marginal distributions.

**Comment by kotania** [comment]
Thank you, Johannes, prior volume effects appear to be the issue exactly. The MLE point is much closer to the true parameter value and is within acceptable margin. Furthermore, I was able to identify something very similar to an L-shaped posterior in a pair of parameters, one of them being my parameter of interest. The posterior maximum in this 2D space is again much closer to the true value than the 1D projection. 

Thanks a lot once again! For anyone else stumbling upon the same issue, Fig. 1 here is a good illustration: https://arxiv.org/pdf/2405.00261
