### ISSUE TITLE
Logging output to a txt-File?

### ISSUE THREAD

**Issue by alexkolo** [JohannesBuchner/UltraNest#2]
Dear Johannes

This might a very trivial thing but do you mind explaining here, how one can pipe the output to txt-file in a simple way?
You describe in [1] a method to redirect the output to a logger but I'm not familiar with this module, making it difficult to find a simple solution to the problem.

[1] https://johannesbuchner.github.io/UltraNest/issues.html#frequently-asked-questions

FYI, I tested ultranest and follow your nice explanation, which was very helpful. So far, it works well. I plan to implement it in a scientific project, which will produce a python fitting tool as one outcome.

**Comment by JohannesBuchner** [comment]
Like this:
```
import logging

logging.basicConfig(filename='app.log', filemode='w', format='%(name)s - %(levelname)s - %(message)s')

# ultranest stuff here
```

By default, there is also a debug.log file created, but that may be a bit noisy.

If you want the stdout text into a file, maybe pipe it somewhere (perhaps with tee) when you run it.

**Comment by alexkolo** [comment]
Thank you. Yes, my main concern is to redirect the `stdout` into a txt-file (but good to know that there is `debug.log`). I typically execute my code as `%run -i code.py` within an `ipython` shell, especially in the development phase, i.e. using `tee` or other piping solutions wouldn't be possible.

I'm aware of the keywords `viz_callback` and `show_status` for `sampler.run` and it's good thing that you implemented them. Ideally, I would like to send the output controlled with `viz_callback` to a text-file, while the output controlled with `show_status` can go to the `stdout`. At the moment, I'm just using `viz_callback=False, show_status=True`.

**Comment by JohannesBuchner** [comment]
These could be useful.
https://stackoverflow.com/questions/11833654/log-ipython-output
https://stackoverflow.com/questions/4675728/redirect-stdout-to-a-file-in-python

**Comment by alexkolo** [comment]
Wow. Cool. That's very helpful. Thanks.
