### ISSUE TITLE
Runtime Warning & Difficulty Recovering Fiducials

### ISSUE THREAD

**Issue by nsusemiehl** [JohannesBuchner/UltraNest#28]
* UltraNest version: 3.2.0
* Python version: 3.8.3
* Operating System: macOS Catalina 10.15.6

### Description
I'm attempting to benchmark the performance of UltraNest for the sake of a comparison to another nested sampling technique, but I'm having a lot of difficulty in recovering the fiducial parameter values of my model even when the error is very low. This is a six dimensional problem with monomodal posteriors and the other nested sampling technique has no problem solving it, but the true parameter values do not fall anywhere near the 2-sigma range of the posteriors found by UltraNest. I've been racking my mind on how I can improve these results, I've double checked that the prior and likelihood functions return what I expect, but I can't find a way to recover the true parameter values. I've encountered a runtime warning which occurs each time the live point display is printed out, and I wonder if this is a cause of the problem:

```
/Users/nsusemie/opt/anaconda3/lib/python3.8/site-packages/ultranest/integrator.py:1921: RuntimeWarning: invalid value encountered in sqrt
  tregion.create_ellipsoid()
```

Is it possible that this warning is an indication of a larger problem? Would you be able to offer any advice that could help me solve this problem?

I'm certainly no expert, so please let me know if any of the above needs to be clarified or if I can provide additional details. Thank you in advance.

**Comment by JohannesBuchner** [comment]
Could you show your prior transforms and likelihood functions?

**Comment by nsusemiehl** [comment]
Thank you for your quick response! Here they are:

```
def pr(cube, pmin, pmax):
    cube = cube.copy()

    for i in range(cube.shape[-1]):
        if np.array_equal(grid_parameters[i][0],P0list) or np.array_equal(grid_parameters[i][0],glist) or np.array_equal(grid_parameters[i][0],Aslist):
            cube[:,i] = cube[:,i] * (pmax[i] - pmin[i]) + pmin[i]
        else:
            cube[:,i] = 10**(cube[:,i] * (np.log10(pmax[i]) - np.log10(pmin[i])) + np.log10(pmin[i]))
    return cube
```

```
def ll(cube, grid, getter, data, uncert, fm):

    forward_start = time.time()

    ymodel = np.apply_along_axis(fm, 1, cube, grid=grid, clear_folder_path=None, cloud_folder_path=None, spectrum_type="albedo", log=[0,1,2,4], get_function=getter)

    forward_durations.append(time.time()-forward_start)

    loglike = -0.5 * (((ymodel - data) / uncert)**2).sum(-1) - np.log10(uncert*np.sqrt(2.0*np.pi))
    return loglike
```

"ymodel" is the model with the parameters given by cube that is approximated by the function "fm" (which takes the parameters grid, clear_folder_path, etc.). This model approximation function was used in the other nested sampling technique I mentioned which was successful (a custom-built interface for Multinest) so I don't think the problem lies here. "data" is the model with the fiducial parameter values I'm trying to recover and for the purpose of this test I set "uncert" to be 1e-4 with the hopes that this low error would allow UltraNest to easily find the correct model parameter values. The prior function uses uniform priors for some of the model parameters and log-uniform for others. I've largely used the default settings for ultranest.ReactiveNestedSampler() and sampler.run(), except I set "vectorized" to be True.

**Comment by JohannesBuchner** [comment]
Put some `assert np.isfinite(cube).all()` before `return cube`.

The warning is harmless, but could indicate that the transformed live points are linearly dependent, or even have the same value. The ellipsoid around the transformed points is only built when the transform is non-linear (I guess the second case of the if in pr applies).

**Comment by nsusemiehl** [comment]
Thank you for this suggestion. I ran UltraNest again but never encountered an assertion error. Also, the same warning as before occurred and the resulting parameter estimates were identical.

Is there a way to include more points in the final posteriors? It seems from the trace plots that there seems to be a lot more variance in the parameter values over the course of the run.

**Comment by JohannesBuchner** [comment]
You also have access to the weighted points (before drawing a equally weighted sample) in the results.

It's hard to tell. Can you code up a minimal python example that reproduces the issue?

**Comment by nsusemiehl** [comment]
I don't think it would be possible to provide a minimal example that reproduces the issue without giving you the data and helper functions I'm using. If you would like me to do so, I can post these to my Github and give you a link, but I understand this may be asking too much.

Perhaps the corner, trace, and run plots will be helpful. To me, it seems like UltraNest has run correctly, but for some reason the results are incorrect (true parameter values do not appear at all in the posterior distributions...)

[corner.pdf](https://github.com/JohannesBuchner/UltraNest/files/6473938/corner.pdf)
[run.pdf](https://github.com/JohannesBuchner/UltraNest/files/6473939/run.pdf)
[trace.pdf](https://github.com/JohannesBuchner/UltraNest/files/6473940/trace.pdf)

**Comment by JohannesBuchner** [comment]
There seems to be some constraint forcing g==10*P0, and the ridge for it is extremely narrow. 
I'd guess that the numerical issues come from that.

Perhaps you can reparameterize with a ratio parameter g=P0*k, free parameters g and k. 

If your likelihood is trying to encode g==10*P0, perhaps drop one of the two parameters and derive it from the other.

**Comment by JohannesBuchner** [comment]
What are the true values?

**Comment by nsusemiehl** [comment]
Thank you for this suggestion. I tried the retrieval with g=P0*k with P0 and k as free parameters. g and P0 must be between 1-100 and 0.71-10 respectively so I made k vary between 1/.71-10. Here are the resulting plots:
[corner.pdf](https://github.com/JohannesBuchner/UltraNest/files/6496815/corner.pdf)
[run.pdf](https://github.com/JohannesBuchner/UltraNest/files/6496816/run.pdf)
[trace.pdf](https://github.com/JohannesBuchner/UltraNest/files/6496817/trace.pdf)

Each of the parameter posteriors still do not include the true values. These are, for H2O, P0, O3, O2, g, and As respectively: 3e-3, 1.0, 7e-7, 0.21, 9.8, and 0.05.

One thing I've observed is that the the spectrum with the retrieved set of parameters has a higher likelihood than the spectrum with the true set of parameters, likely due to the inaccuracies in the function I use to approximate spectra. Is it true that parameters found via nested sampling/UltraNest (medians of the posteriors) correspond with the highest likelihood? If so, I can see why. Ultranest leads to the answer it does. What confuses me further is the the implementation that uses Multinest _was_ able to retrieve the correct parameter values, and I use the same form of the likelihood function with my UltraNest retrieval as was used by the Multinest retrieval.

**Comment by JohannesBuchner** [comment]
Ok, seems like you need to debug the two function implementations to find out why they give the numbers they do at the two locations.

If the difference in loglikelihood is substantial (say, >2), given flat priors I wouldn't be surprised if the posterior peaks follow the maximum likelihood.

**Comment by nsusemiehl** [comment]
It seems like this issue with the likelihood may be the underlying problem and not something with UltraNest. The likelihood of the correct set of parameter values is -13570 and the likelihood of the retrieved set of parameters is -336, and I'm using flat priors. I've also tried this same problem with emcee and it retrieved a very similar set of parameters as UltraNest. 

It's still odd to me that the implementation using MultiNest was able to retrieve the correct parameters. Perhaps there is some difference between how UltraNest and MultiNest work that may have an effect here. I'll investigate this, but thank you very much for your help here Johannes. I greatly appreciate you taking the time to talk through this with me.

**Comment by JohannesBuchner** [comment]
Yeah, I suspect you have some bug somewhere with how the floats are passed here between the functions. For example ultranest expects a 1-parameter function which returns a fresh numpy array, while multinest expects you to modify the array in place. 
You can also try with the pymultinest solver interface (accepts the same functions as ultranest) https://github.com/JohannesBuchner/PyMultiNest/ if you want to separate different interfaces vs samplers.

**Comment by JohannesBuchner** [comment]
If this is still an issue and you have more information, please reopen.
