### ISSUE TITLE
Error upon importing ultranest

### ISSUE THREAD

**Issue by nenasedk** [JohannesBuchner/UltraNest#29]
* UltraNest version: 3.2.0
* Python version: 3.7
* Operating System: macOS 10.14.6

### Description

Describe what you were trying to get done.

Trying to import ultranest.

Tell us what happened, what went wrong, and what you expected to happen.
There is a valueError upon import:
```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-b7f2dc2ff625> in <module>
----> 1 import ultranest
      2 #import species
      3 import numpy as np
      4 from astropy.io import fits
      5 #species.SpeciesInit()

~/anaconda3/lib/python3.7/site-packages/ultranest/__init__.py in <module>
      5 """
      6 
----> 7 from .integrator import NestedSampler, ReactiveNestedSampler, read_file
      8 from .utils import vectorize
      9 

~/anaconda3/lib/python3.7/site-packages/ultranest/integrator.py in <module>
     18 
     19 from .utils import create_logger, make_run_dir, resample_equal, vol_prefactor, vectorize, listify as _listify, is_affine_transform, normalised_kendall_tau_distance
---> 20 from ultranest.mlfriends import MLFriends, AffineLayer, ScalingLayer, find_nearby, WrappingEllipsoid
     21 from .store import HDF5PointStore, TextPointStore, NullPointStore
     22 from .viz import get_default_viz_callback, nicelogger

~/anaconda3/lib/python3.7/site-packages/ultranest/mlfriends.pyx in init ultranest.mlfriends()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject```

### What I Did

```
import ultranest
```

This happened from a clean conda environment, using pip install ultranest to install the package.

**Comment by JohannesBuchner** [comment]
Install ultranest from conda.

The command is in https://johannesbuchner.github.io/UltraNest/installation.html after 
"If you use conda, you can install UltraNest with:"

**Comment by MuellerSeb** [comment]
This could be solved by building the cython extensions with https://github.com/scipy/oldest-supported-numpy

See: https://github.com/JohannesBuchner/UltraNest/issues/26

**Comment by tomasstolker** [comment]
I ran into the same issue on a Linux machine. I tried `python3 setup.py build_ext --inplace` but the problem remained.

**Comment by JohannesBuchner** [comment]
Please report what `conda install ultranest` followed by `python3 -c 'import ultranest'` produces, in a fresh conda environment.

Please report what `pip3 install ultranest` followed by `python3 -c 'import ultranest'` produces, in a fresh conda environment.

Please report what `python3 setup.py install` followed by `python3 -c 'import ultranest'` produces, in a fresh conda environment.

**Comment by nenasedk** [comment]
For all tests I use a new conda env, using python 3.8 on macoS 10.14.6
I have not used the 'https://github.com/scipy/oldest-supported-numpy' as recommended above.

In a clean conda env, `conda install ultranest`  seems to install properly, there is no printed output after `python3 -c 'import ultranest'`

In a clean conda env `pip3 install ultranest` failes to install, and instead produces a loop of the following error:
```WARNING: Discarding https://files.pythonhosted.org/packages/c7/b0/b17c9cd2e7fb3d11cdc0f26b4e7aff4a1a3a881e062b30ce4cdbcf724a7d/ultranest-3.2.1.tar.gz#sha256=084514ef45cdc55122b663dab29bd2306a8d07b5253d6ad1acce0cb2c9843ae8 (from https://pypi.org/simple/ultranest/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached ultranest-3.2.0.tar.gz (21.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /Users/nasedkin/anaconda3/envs/untest/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zb/1kks1nb14h7_f6zq97b6sg8xxc6_b4/T/pip-install-rnrd2lm_/ultranest_3a6b8defbf954e308b5d06b1fd5417aa/setup.py'"'"'; __file__='"'"'/private/var/folders/zb/1kks1nb14h7_f6zq97b6sg8xxc6_b4/T/pip-install-rnrd2lm_/ultranest_3a6b8defbf954e308b5d06b1fd5417aa/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zb/1kks1nb14h7_f6zq97b6sg8xxc6_b4/T/pip-pip-egg-info-721ertg1
         cwd: /private/var/folders/zb/1kks1nb14h7_f6zq97b6sg8xxc6_b4/T/pip-install-rnrd2lm_/ultranest_3a6b8defbf954e308b5d06b1fd5417aa/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zb/1kks1nb14h7_f6zq97b6sg8xxc6_b4/T/pip-install-rnrd2lm_/ultranest_3a6b8defbf954e308b5d06b1fd5417aa/setup.py", line 9, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
```

The module is not imported, but no error is printed when running `python3 -c 'import ultranest'`
If I `conda install cython` in the clean env before pip3 installing ultranest, the installation is sucessful, although there is an error:
```1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ultranest
```

If I `python3 setup.py install` ultranest from its directory in a clean env, on the up-to-date master branch, it throws an error, since cython is not installed. After conda installing cython, `python3 -c 'import ultranest'` produces an error, since the requirements still need to be installed. After `pip install -r  pip-requirements.txt`, `python3 -c 'import ultranest'` still produces an error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/nasedkin/python-packages/ultranest/ultranest/__init__.py", line 7, in <module>
    from .integrator import NestedSampler, ReactiveNestedSampler, read_file
  File "/Users/nasedkin/python-packages/ultranest/ultranest/integrator.py", line 20, in <module>
    from ultranest.mlfriends import MLFriends, AffineLayer, ScalingLayer, find_nearby, WrappingEllipsoid, RobustEllipsoidRegion
ModuleNotFoundError: No module named 'ultranest.mlfriends'
```

Using `python3 setup.py build_ext --inplace` appears to have resolved this final error.

**Comment by tomasstolker** [comment]
I created a new `virtualenv` (using Python 3.8 on a Linux machine) and emptied the `pip` cache. Then I installed `cython` with `pip` and afterwards `UltraNest`. This gave the following error:

```
  ultranest/mlfriends.c:612:10: fatal error: numpy/arrayobject.h: No such file or directory
    612 | #include "numpy/arrayobject.h"
        |          ^~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ultranest
```

But it finished the installation nonetheless:

`Running setup.py install for ultranest ... done`

Importing does not give an error anymore! Not quite sure what solved the issue but happy that it works now :).
