### ISSUE TITLE
Should overcluster data go into log_dir?

### ISSUE THREAD

**Issue by andrewfowlie** [JohannesBuchner/UltraNest#3]
* UltraNest version: 2.02
* Python version: 3.6.8
* Operating System: Ubuntu 18

### Description

On some problems, ultranest produces a lot of files called `overclusted*{.txt, .npz}` that don't go into the `log_dir` directory, and I can't control where they are saved. My guess is that it's these lines

https://github.com/JohannesBuchner/UltraNest/blob/c59daf8d59e6c3c647f358944393545bcec0fe57/ultranest/integrator.py#L1454

and that probably that the name should be preceded by `log_dir`

### What I Did

I can make a reproducible example if necessary, but basically I run ultranest on the classic eggbox problem which has lots of modes.

**Comment by JohannesBuchner** [comment]
This is already commented out in the last release. 

Many modes like in eggbox are not a problem.

Sometimes the clustering/mlfriends radius combination did produce a large number of extra modes. I mitigated this with some changes, but perhaps not fully understood. The nominal number of clusters may be temporarily high, but the calculation resumes correctly in any case.
