### ISSUE TITLE
Slower with MPI?

### ISSUE THREAD

**Issue by varunmathurv** [JohannesBuchner/UltraNest#37]
* UltraNest version:3.3.0
* Python version:3.8.8
* Operating System: Red Hat Enterprise Linux Server 7.7

I'm running UltraNest/MultiNest on GALPROP, a numerical code for calculating cosmic ray propogation. I vary upto 10 parameters with flat priors. I wrote a likelihood function which runs GALPROP(creates an input file, reads the output file), and compares the output to data. I have attached the likelihood function below.

```
def loglikelihood(cube):

    identity = secrets.token_hex(4) 

    # generate job id

    # create galdef file
    create_galdef(cube, identity)

    # run galprop
    galprop = os.system('/home/varun/galprop/bin/galprop -r {} -f /home/varun/galprop/FITS -g /work/varun/GALDEF -o /work/varun/output'.format(identity))

    # delete galdef file
    os.remove('/work/varun/GALDEF/galdef_56_{}'.format(identity))

    # calculate chi2
    if galprop == 0:
        galprop_model = fits.open('/work/varun/output/nuclei_56_{}.gz'.format(identity))[0].data[0,:,0,10]/(galprop_energy*1000)**2*1e7

        os.remove('/work/varun/output/nuclei_56_{}.gz'.format(identity))
        galp = splrep(galprop_energy,galprop_model)
        dampe_model = splev(dampe_energy,galp)
        ams_model = splev(ams_energy,galp)
        ams_chi2 = ((ams_data-ams_model)**2/(ams_error)**2)[22:]
        dampe_chi2 = ((dampe_data-dampe_model)**2/(dampe_error)**2)
        chi2value=np.sum(ams_chi2)+np.sum(dampe_chi2)

        return -chi2value/2
```

Each evaluation of the likelihood takes 2.5 seconds on the cluster.

When I run this in **parallel** with either UltraNest/MultiNest, it actually **slows down** the code with each additional CPU. I checked that both UltraNest/MultiNest have a single header in the output, and in fact achieved speedup with the example problems in parallel. I picked the bash script from [Scaling when parallelizing?#142](https://github.com/JohannesBuchner/PyMultiNest/issues/142) and tested parallizing the example problem mentioned there. I achieved speedup as expected. 

```
#!/bin/bash
#SBATCH --job-name=Ultranest
#SBATCH --output=Ultranest-%j.out
#SBATCH --error=Ultranest-%j.err
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --time=01:00:00


mpiexec -n 4 Utragalproptest1.py
```

What can be causing this slowing down of the script with mpi? I'm considering following your solution to [#36
](https://github.com/JohannesBuchner/UltraNest/issues/36) but I've got no experience with parallelization and I'm unsure if this 
`from joblib import delayed, Parallel` can be used with the above submit script and whether mpi usage of UltraNest or MultiNest will clash with this parallelization.
I have access to a lot of cores and core hours but can only run a single code for 6 days.
Thanks,
-Varun

**Comment by JohannesBuchner** [comment]
If you parallelise with MPI, you should not also parallelise within your likelihood. Try setting OMP_NUM_THREADS=1 to avoid over-committing. Each galprop should only use a single core. Have an eye on the load.
