### ISSUE TITLE
Model comparison example typo

### ISSUE THREAD

**Issue by mattpitkin** [JohannesBuchner/UltraNest#38]
In the [model comparison example](https://johannesbuchner.github.io/UltraNest/example-sine-modelcomparison.html) the comment above the prior transform for the period says it goes from 0.3 to 30, when the actual prior transform goes from 1 to 100 (see below).

```python
def prior_transform1(cube):
    # the argument, cube, consists of values from 0 to 1
    # we have to convert them to physical scales

    params = cube.copy()
    # let background level go from -10 to +10
    params[0] = cube[0] * 20 - 10
    # let amplitude go from 0.1 to 100
    params[1] = 10**(cube[1] * 3 - 1)
    # let period go from 0.3 to 30
    params[2] = 10**(cube[2] * 2)
    # let time go from 0 to 1
    params[3] = cube[3]
    return params
```

The comment should either be changed, or the prior transform changed to be `params[2] = 10**(cube[2] * 2 + np.log10(0.3))`. It's probably also worth noting (for more novice users) that the amplitude and period prior transforms represent uniform in log priors.

**Comment by JohannesBuchner** [comment]
Thank you for spotting this! Much appreciated. I'll change the comment.

**Comment by JohannesBuchner** [comment]
Finally I fixed this!
