### ISSUE TITLE
Generating results from points.hdf5

### ISSUE THREAD

**Issue by smutch** [JohannesBuchner/UltraNest#39]
* UltraNest version: 3.3.0
* Python version: 3.9.6
* Operating System: NA

---

First off, thanks for a great and very comprehensive package!

I was wondering if it is possible (/ how is best) to generate results (`chains/*`, `info/*`, etc.) from a `points.hdf5` file without the need to re-evaluate the likelihood?

My use case is that I have a very long MPI run going which regularly times out on the job queue. This run requires several GPU-enabled nodes to evaluate the likelihood (meaning long wait times to get my jobs allocated) and therefore I would like to be able to generate intermediate results from the run without needing to set `max_iters`/`max_ncalls` and restart it with the resources necessary to evaluate the likelihood.

I've a feeling that there should be some combination of integrator parameters (`num_test_samples`, `max_iters`, `max_num_improvement_loops` etc.) that will provide me with the desired result, but I can't figure out what they are...

**Comment by JohannesBuchner** [comment]
Yes, I think those are the right parameters, and their values should be something like 0, number of items in points.hdf5 minus number of live points, 0). There is also a function to read a points.hdf5 file (`read_file`).

To achieve your goal, I would recommend you to use run_iter() instead, something like this:

```
niter = 0
while True:
      for results in sampler.run_iter(max_iters=niter, ...):
            print(results)
      niter += 1000
```

However, for most of the run (while at 0%) all of the probability is concentrated in the point with the highest likelihood discovered so far. That point can be easily read out from the hdf5 file.

**Comment by smutch** [comment]
Hi @JohannesBuchner. Thanks for your help with this. I'm trying to implement something along the lines of your recommendation (to use `run_iter`), however, I am having some issues getting this approach to work...

It seems that the `for` loop is never broken out of and the sampler never convergences. I can get things to work if I set and increment `max_ncalls` instead, however, this seems to result in a much less efficient sampling (significantly more evaluations required to achieve convergence).

For example, if I set up the basic usage problem as provided in the [documentation](https://johannesbuchner.github.io/UltraNest/using-ultranest.html), `sampler.run()` achieves convergence in 14,905--16,000 evaluations. If I use

```python
sampler = ultranest.ReactiveNestedSampler(
    param_names, my_likelihood, my_prior_transform
)

ncalls = 1000
while True:
    for result in sampler.run_iter(max_ncalls=ncalls):
        pass
    ncalls += 1000
```

then it takes at least 20,000 evaluations for convergence (~33% increase). Since my evaluations are computationally expensive, I'm looking to limit the number as much as possible.

Is there any way I can implement this method without increasing the number of required evaluations significantly?

This also raises the question for me, does a restart using `resume='resume'` also result in many more required likelihood evaluations to attain convergence? (I'll try and do some testing of this, but thought I'd ask here in case you know the answer off the top of your head.)

**Comment by JohannesBuchner** [comment]
This kind of for loop over run_iter is the same thing `run()` uses internally (you can check the code).

33% may be within the variance of runs. resume='resume' should not require more likelihood evaluations. But regions being built may come out slightly larger/smaller in one (re)run compared to the next, that's why you may see fluctuations.

You probably want to set `frac_remain=0.5` and `max_num_improvement_loops=0`.

I don't recall if `max_ncalls` refers to new model evaluations or total model evaluations.

**Comment by smutch** [comment]
`max_num_improvement_loops=0` was the key. I also realized that the default parameters of `run_iter` are not the same as `run`. After addressing this, I was able to do a staged run with a comparable number of model evaluations as what I was getting with calling `sampler.run`, as well as get the run to terminate automatically:

```python
max_iters=500
cont = True
prev_niter = 0
while cont:
    for result in sampler.run_iter(
        update_interval_volume_fraction=0.8,
        update_interval_ncall=None,
        log_interval=None,
        show_status=True,
        viz_callback="auto",
        dlogz=0.5,
        dKL=0.5,
        frac_remain=0.01,
        Lepsilon=0.001,
        min_ess=400,
        max_iters=max_iters,
        max_ncalls=None,
        max_num_improvement_loops=0,
        min_num_live_points=400,
        cluster_num_live_points=40,
        insertion_test_window=10,
        insertion_test_zscore_threshold=4,
    ):
        if result['niter'] == prev_niter:
            cont=False
        prev_niter = result['niter']
            
    max_iters+=500
```

Thanks again for your help and for your patience!
