### ISSUE TITLE
Unable to start runs when using MPI

### ISSUE THREAD

**Issue by ajdittmann** [JohannesBuchner/UltraNest#4]
* UltraNest version: 2.0.4
* Python version: 3.7.4
* Operating System: CentOS Linux 7 (Core)
* MPI version: OpenMPI 3.1.3, (OpenRTE)
* h5py version: 2.9.0

### Description
When I attempt to run the 100-D Gaussian example using MPI,
> mpirun -np 2 python3 gauss.py --x_dim=100 --num_live_points=400 --slice --slice_steps=100

the following OSError occurs:
>   File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)

During the handling of this exception, other exceptions occur. I have included the full report [here.](https://github.com/JohannesBuchner/UltraNest/files/4168228/ultranest_error_log.TXT)

The example ran fine without MPI. I renamed the logs directory before running this. The error occurred both with and without setting OMP_NUM_THREADS=1

**Comment by JohannesBuchner** [comment]
Do you have mpi4py installed?

Can you reproduce with

    python3 -c "h5py.File('testfile.h5', mode='a')"
    mpirun -np 2 python3 -c "h5py.File('testfile.h5', mode='a')"

I wonder if your hdf5 library may not be compiled with MPI capabilities.

**Comment by ajdittmann** [comment]
It looks like hdf5 wasn't compiled for parallel use (using h5cc to check) . I'll reopen the issue if the problem persists after sorting that out.
