### ISSUE TITLE
Number of live points decreases below `min_num_live_points` parameter

### ISSUE THREAD

**Issue by warrickball** [JohannesBuchner/UltraNest#40]
* UltraNest version: 3.3.0
* Python version: 3.9.6
* Operating System: Fedora 33

### Description

I'm running an experiment and finding that immediate after I start a run, the number of live points appears to drop from the value I provide (usually 400) to around ~80, where it remains for the rest of the run (unless an improvement loop later decides to increase it). I'm not sure if this is expected for some reason but it isn't what the documentation implies.

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

I haven't devised a MWE yet and my example involves dependencies on a lot of yet-unreleased code and a few hundred MB of data, but this is what the main block looks like

```
S = ultranest.ReactiveNestedSampler(names, log_likelihood, prior_transform,
                                    log_dir=log_dir, ndraw_min=512,
                                    num_test_samples=50)
S.stepsampler = ultranest.stepsampler.RegionSliceSampler(nsteps=2*D) # D=12

r = S.run(min_num_live_points=400, dKL=0.5, dlogz=0.5)
S.print_results()
```
The first running summary lines of terminal output already end with `N=84`, where I'd expect at least `N=400`.

**Comment by JohannesBuchner** [comment]
This happens when you have a likelihood plateau.

Probably you are setting a small value when the nominal likelihood computation went wrong. Use something that increases slightly towards good values.

**Comment by JohannesBuchner** [comment]
I have recently added debug log messages to highlight this, but that is not in the release yet, I think.

**Comment by warrickball** [comment]
You're absolutely right! The likelihood evaluation involves interpolation on a grid and if the argument is out of bounds I return a tiny constant log-likelihood of -10³⁰⁰. I'll try something that (very gently) slopes towards the centre of the grid later today. Thanks for the quick and insightful reply!

**Comment by warrickball** [comment]
Your suggestion has worked. I've now got the requested number of live walkers from the start. Thanks again.
