### ISSUE TITLE
Ultranest for correlated error

### ISSUE THREAD

**Issue by subhratadey** [JohannesBuchner/UltraNest#41]
Hello, I am quite novice to the concept of bayesian analysis and specifically Ultranest. I plan to use ultranest for spectral modeling of radio fluxes with correlated noise and model comparison. In the example provided for ultranest tutorial, the errors are independent and models are computed accordingly. Could you kindly guide me how I can approach ultranest with correlated error.

**Comment by JohannesBuchner** [comment]
In case of correlated Gaussian noise, you want to use Gaussian processes to model the residuals.

A good and free book is https://www.gaussianprocess.org/gpml/

A easy-to-use library is https://george.readthedocs.io/ which has a good introduction tutorial. See also celerite for a more limited subset that computes a bit faster.

Modelling with this will allow you to compute a log-likelihood. You can then pass your likelihood function to UltraNest to explore it.
