### ISSUE TITLE
For help

### ISSUE THREAD

**Issue by senmaaa** [JohannesBuchner/UltraNest#49]
* UltraNest version:lasted
* Python version:3.7
* Operating System:ubuntu

### Description

How can I do when the number of a model's params more than 323? 

### What I Did

the cube has length 323. when there are more params，what can do to avoid problem below?
![图片](https://user-images.githubusercontent.com/44462000/143987781-2b47d233-c503-4307-9664-70dbc2da2749.png)

Thanks  for your time!

**Comment by JohannesBuchner** [comment]
Is len(paramnames) > 323?

**Comment by senmaaa** [comment]
> Is len(paramnames) > 323?

yes。

**Comment by JohannesBuchner** [comment]
If you are using vectorized=True, the my_prior_transform function is not correctly defined. It should be `params[:,323] = cube[:,323] * 200 - 100`.

**Comment by senmaaa** [comment]
In my opinion, the problem is that the maximum cube length is 323.But model have  parameters >323.

**Comment by JohannesBuchner** [comment]
Can you print out the shape of cube and params?

**Comment by senmaaa** [comment]
Thank you very much！
It was my code fault。

**Comment by JohannesBuchner** [comment]
Ok, good, I'll close this then.
