### ISSUE TITLE
what is equivalent of random walk steps in ultranest

### ISSUE THREAD

**Issue by subhratadey** [JohannesBuchner/UltraNest#53]
* UltraNest version:
* Python version:
* Operating System:

### Description

I want to have a fixed number of values for free parameters for each run. I am aware that in emcee package that is done by setting the step number. Could you kindly tell me how I can obtain a similar result in ultranest package? 

### What I Did

I tried setting the steps and max_nsteps variables but it didn't help.

**Comment by JohannesBuchner** [comment]
I don't quite understand what you want to do. Do you want to force a fixed computation budget? That's not easily possible with nested sampling, but there are a few parameters that you can adapt to stop after a fixed number of calls.

Have a look at the run() parameters
https://johannesbuchner.github.io/UltraNest/ultranest.html#ultranest.integrator.ReactiveNestedSampler.run
especially:
* min_num_live_points (similar to the number of walkers)
* max_ncalls, max_iters
* frac_remain=0.5

It is likely that if you ask nested sampling to terminate early, all posterior weight is still concentrated in one of the live points, so you cannot resolve the posterior. Nevertheless, comparing the live points to the prior will give you relevant information.
