### ISSUE TITLE
Latex symbol for cornerplot

### ISSUE THREAD

**Issue by subhratadey** [JohannesBuchner/UltraNest#66]
* UltraNest version:
* Python version:
* Operating System:

### Description

Is it possible to include latex/maths symbols in the ultranest corner plots such as lambda, sigma, etc

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by subhratadey** [comment]
I tried using \mathrm, but it gave an error.

**Comment by JohannesBuchner** [comment]
Yes, it works the same as with matplotlib text labels ('$\lambda$').
