### ISSUE TITLE
Totally Silent Running

### ISSUE THREAD

**Issue by PBGraff** [JohannesBuchner/UltraNest#7]
* UltraNest version: 2.1.2
* Python version: 3.7
* Operating System: Mac OSX 10.14

### Description

While I can turn off the dynamic visualization when performing a run, there are still other logging messages being output to stdout. I'd like to be able to run completely silently (on stdout) since I have a larger number of models to fit.

**Comment by JohannesBuchner** [comment]
You should be able to get the logger `getLogger('ultranest')`
https://docs.python.org/3.5/library/logging.html
and configure it. For example, you can set its level to ERROR.
If you specify a handler (for example filehandler) for it, ultranest will not add any additional handlers.

**Comment by PBGraff** [comment]
OK, I couldn't get that to work before, but it is now. Maybe an option for setting the handler or logging level would make this easier for users. Not a priority, though.

**Comment by JohannesBuchner** [comment]
Yes, probably this is a good idea ultimately. I am trying to aim for a middle ground between useful stdout messages for first-time users and ability to integrate and control ultranest inside larger frameworks.
