### ISSUE TITLE
Importing the chain file to Xspec manually

### ISSUE THREAD

**Issue by kchoX14** [JohannesBuchner/UltraNest#72]
* UltraNest version: 3.4.6
* Python version: 3.9.12
* Operating System: Linux Ubuntu 18.04 LTS, kernel v5.7.1-050701-generic

### Description

After an _Ultranest_ run, which is the chain file than can be imported outside the Python environment for external processing of the Monte Carlo samples over Xspec directly? _Please note that I am using UltraNest over **threeML**, not **BXA**_.

There are three text (not FITS) files available with parameter samples inside the `/chains` sub-directory (one of the 5 auto-generated to store the results in):
-  `equal_weighted_post.txt`
-  `weighted_post.txt`
-  `weighted_post_untransformed.txt`. 

The last file is the `run.txt`, which contains the statistical bits. 

The `/info` sub-directory has the posterior summary file (`post_summary.csv`) and a `results.json` file.

The sub-directories `/extra` and `/plots` are empty.

Another is the `points.hdf5` file within the `/results` sub-directory. Is that the file I should convert to FITS and then use over Xspec? 

**Requirement** 
Knowing which file is the correct one is essential to me, since I could then try to sample on Xspec to _compute the equivalent width of my line model component_ directly on Xspec. The threeML developers suggested I should ask this question here.

**Comment by JohannesBuchner** [comment]
The output files are described in https://johannesbuchner.github.io/UltraNest/performance.html#output-files
