### ISSUE TITLE
Model comparison

### ISSUE THREAD

**Issue by subhratadey** [JohannesBuchner/UltraNest#83]
* UltraNest version:
* Python version:
* Operating System:

### Description

I am using the Ultranest package. For model comparison, is it physical/okay to consider models with a higher number of free parameters compared to the number of data points? In my case, the model with a higher free parameter is fitting data well (the number of the data point is less than the number of the free parameter). How can I take care of this overfitting problem?

**Comment by JohannesBuchner** [comment]
Yes, that's fine. The parameter uncertainties may indicate that some aspects of the model could not be constrained by the data.
