### ISSUE TITLE
Conda installer for osx-arm64

### ISSUE THREAD

**Issue by JorisDeRidder** [JohannesBuchner/UltraNest#87]
Thanks for this great library!
I have difficulties, however, to install UltraNest on OSX with Apple Silicon.  
Do you foresee to provide a conda-installable version of UltraNest for osx-arm64 in the near future? 
```
❯ conda install -c conda-forge ultranest                                                                                                            (course)
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - ultranest

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch
  ```

**Comment by JohannesBuchner** [comment]
Do you know what is missing to achieve that?

**Comment by JorisDeRidder** [comment]
I'm afraid not, but meanwhile I got UltraNest working on OSX-arm64 using the pip installer. I did had to make sure that I didn't also install PyMC in the same environment, but this seems a conda problem, not an UltraNest problem.

I'll leave it up to you to either choose to close this issue (and perhaps add a pointer in the docs) or to leave it as an open issue.

**Comment by JohannesBuchner** [comment]
I suspect that conda-forge may need to add builders for that architecture. In the meantime, pip should work.
