### ISSUE TITLE
Using PredictionBand with pre-defined axes

### ISSUE THREAD

**Issue by pboorm** [JohannesBuchner/UltraNest#9]
* UltraNest version: 2.1.2
* Python version: 3.7
* Operating System: Mac OS X 10.14.6

### Description

I have defined multiple axes in matplotlib, and I would like to plot the UltraNest PredictionBand shading on one of those specific axes. Is there a way to pass a specific set of axes to the keywords in PredictionBand to ensure the shading is plotted in the right place? Currently without specifying an axis, the shading is plotted on the last axis that was created.

### What I Did

Following on from the intrinsic distribution example here:
https://johannesbuchner.github.io/UltraNest/example-intrinsic-distribution.html

For the last example (in cell 11 on the webpage above) for using PredictionBand, I am looking to plot the shading on ax1 in the following example:
```
fig = plt.figure(figsize = (14., 7.))
gs = gridspec.GridSpec(1, 2, width_ratios = [1., 1.])
ax1 = fig.add_subplot(gs[0, 0])
ax2 = fig.add_subplot(gs[0, 1])

from ultranest.plot import PredictionBand
x = np.linspace(-100, 100, 400)
band = PredictionBand(x)

for params in sampler.results['samples'][:40]:
    mean, scatter = params
    band.add(scipy.stats.norm(mean, scatter).pdf(x))

band.shade(color='k', alpha=0.1) ## this appears on ax2, not ax1
band.line(color='k')
```

**Comment by JohannesBuchner** [comment]
I think you need to activate the axis you want to plot to, with plt.sca(ax) before calling shade or line.

**Comment by pboorm** [comment]
Perfect -- thanks a lot!
