### ISSUE TITLE
Pass parameters to loglike and prior transform

### ISSUE THREAD

**Issue by QZGao** [JohannesBuchner/UltraNest#94]
* UltraNest version: 3.5.5
* Python version: 3.9.7
* Operating System: Windows 11

### Description

How can I pass parameters to loglike and prior transform functions? Is there such a feature?

**Comment by JohannesBuchner** [comment]
have a look here: https://github.com/JohannesBuchner/UltraNest/issues/51#issuecomment-1103661731

**Comment by QZGao** [comment]
Thanks, great solution 🙂
